stages:
  - build
  - test
  - upload

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - build/

test:
  stage: test
  script: npm test
