export const CART_IS_LOADING = 'CART_IS_LOADING';
export const CART_ITEMS = 'CART_ITEMS';
export const CART_ALL = 'CART_ALL';
export const CART_SUMMARY = 'CART_SUMMARY';
export const CART_HAS_ERRORED = 'CART_HAS_ERRORED';
export const CART_IS_UPDATING = 'CART_IS_UPDATING';

export const AUTH_DROPDOWN_VISIBILITY = 'AUTH_DROPDOWN_VISIBILITY';

export const ADDRESS_PARAMS = 'ADDRESS_PARAMS';

export const ORDERS_IS_LOADING = 'ORDERS_IS_LOADING';
export const ORDERS = 'ORDERS';
export const ORDERS_HAS_ERRORED = 'ORDERS_HAS_ERRORED';
export const ORDERS_IS_UPDATING = 'ORDERS_IS_UPDATING';
export const ORDER_IS_LOADING = 'ORDER_IS_LOADING';
export const ORDER_IS_PLACING = 'ORDER_IS_PLACING';
export const ORDER_HAS_ERRORED = 'ORDER_HAS_ERRORED';
export const ORDER_IS_UPDATING = 'ORDER_IS_UPDATING';
export const ORDER_PAYMENT_SRC = 'ORDER_PAYMENT_SRC';
export const ORDER_PAYMENT_IS_LOADING = 'ORDER_PAYMENT_IS_LOADING';
export const ORDER_ID = 'ORDER_ID';
export const ORDER_COMMENT = 'ORDER_COMMENT';

export const DELIVERY_IS_LOADING = 'DELIVERY_IS_LOADING';
export const DELIVERY_METHODS = 'DELIVERY_METHODS';
export const DELIVERY_HAS_ERRORED = 'DELIVERY_HAS_ERRORED';
export const DELIVERY_IS_UPDATING = 'DELIVERY_IS_UPDATING';
export const DELIVERY_TYPE = 'DELIVERY_TYPE';

export const PAYMENT_IS_LOADING = 'PAYMENT_IS_LOADING';
export const PAYMENT_METHODS = 'PAYMENT_METHODS';
export const PAYMENT_HAS_ERRORED = 'PAYMENT_HAS_ERRORED';
export const PAYMENT_IS_UPDATING = 'PAYMENT_IS_UPDATING';

export const RECIPIENTS_IS_LOADING = 'RECIPIENTS_IS_LOADING';
export const RECIPIENTS = 'RECIPIENTS';
export const RECIPIENTS_HAS_ERRORED = 'RECIPIENTS_HAS_ERRORED';
export const RECIPIENTS_IS_UPDATING = 'RECIPIENTS_IS_UPDATING';
export const RECIPIENTS_IS_ADDING = 'RECIPIENTS_IS_ADDING';
export const RECIPIENTS_ADD_SUCCESS = 'RECIPIENTS_ADD_SUCCESS';
export const RECIPIENTS_ADD_HAS_ERRORED = 'RECIPIENTS_ADD_HAS_ERRORED';

export const PROMO_IS_LOADING = 'PROMO_IS_LOADING';
export const PROMO = 'PROMO';
export const PROMO_HAS_ERRORED = 'PROMO_HAS_ERRORED';
export const PROMO_NEED_AUTH = 'PROMO_NEED_AUTH';
export const PROMO_HAS_FAILED = 'PROMO_HAS_FAILED';

export const ADDING_TO_CART = 'ADDING_TO_CART';
export const ADD_TO_CART_SUSSESS = 'ADD_TO_CART_SUSSESS';
export const ADD_TO_CART_HAS_ERRORED = 'ADD_TO_CART_HAS_ERRORED';

export const PRE_ORDERING = 'PRE_ORDERING';
export const PRE_ORDER_STATUS = 'PRE_ORDER_STATUS';
export const PRE_ORDER_FINALLY = 'PRE_ORDER_FINALLY';

export const ADDRESSES_IS_LOADING = 'ADDRESSES_IS_LOADING';
export const ADDRESSES = 'ADDRESSES';
export const ADDRESSES_HAS_ERRORED = 'ADDRESSES_HAS_ERRORED';
export const ADDRESSES_IS_UPDATING = 'ADDRESSES_IS_UPDATING';
export const ADDRESSES_IS_ADDING = 'ADDRESSES_IS_ADDING';
export const ADDRESSES_ADD_SUCCESS = 'ADDRESSES_ADD_SUCCESS';
export const ADDRESSES_ADD_HAS_ERRORED = 'ADDRESSES_ADD_HAS_ERRORED';

export const GEO_IP_IS_LOADING = 'GEO_IP_IS_LOADING';
export const GEO_IP_DATA = 'GEO_IP_DATA';
export const GEO_IP_HAS_ERRORED = 'GEO_IP_HAS_ERRORED';

export const PICK_UP_POINTS = 'PICK_UP_POINTS';
export const PICK_UP_POINTS_IS_LOADING = 'PICK_UP_POINTS_IS_LOADING';
export const PICK_UP_POINTS_HAS_ERRORED = 'PICK_UP_POINTS_HAS_ERRORED';

export const USER_HAS_ERRORED = 'USER_HAS_ERRORED';
export const USER_IS_LOADING = 'USER_IS_LOADING';
export const USER_IS_AUTH = 'USER_IS_AUTH';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_IS_UPDATING = 'USER_IS_UPDATING';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_ERRORS = 'USER_LOGIN_ERRORS';
export const USER_RESTORE_REQUEST = 'USER_RESTORE_REQUEST';
export const USER_RESTORE_ERRORS = 'USER_RESTORE_ERRORS';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_ERRORS = 'USER_REGISTER_ERRORS';
export const USER_REGISTER_HAS_ERRORED = 'USER_REGISTER_HAS_ERRORED';
export const USER_FAST_REGISTER_HAS_ERRORED = 'USER_FAST_REGISTER_HAS_ERRORED';
export const USER_FAST_REGISTER_REQUEST = 'USER_FAST_REGISTER_REQUEST';
export const USER_FAST_REGISTER_ERRORS = 'USER_FAST_REGISTER_ERRORS';
export const USER_FAST_REGISTER_FORM = 'USER_FAST_REGISTER_FORM';
export const USER_CHANGE_PASS_REQUEST = 'USER_CHANGE_PASS_REQUEST';
export const USER_CHANGE_PASS_ERRORS = 'USER_CHANGE_PASS_ERRORS';
export const USER_RESTORE_SUCCESS = 'USER_RESTORE_SUCCESS';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_SUBSCRIPTION_IS_UPDATING = 'USER_SUBSCRIPTION_IS_UPDATING';
export const USER_UPDATE_ERRORS = 'USER_UPDATE_ERRORS';
export const USER_RESTORE_HAS_ERRORED = 'USER_RESTORE_HAS_ERRORED';
export const USER_LOGOUT_HAS_ERRORED = 'USER_LOGOUT_HAS_ERRORED';
export const USER_LOGOUT_ERRORS = 'USER_LOGOUT_ERRORS';
export const USER_CHANGE_PASS_HAS_ERRORED = 'USER_CHANGE_PASS_HAS_ERRORED';
export const USER_ERRORS = 'USER_ERRORS';
export const USER_SUBSCRIPTION_HAS_ERRORED = 'USER_SUBSCRIPTION_HAS_ERRORED';
export const USER_SUBSCRIPTION_ERRORS = 'USER_SUBSCRIPTION_ERRORS';
export const USER_UPDATE_HAS_ERRORED = 'USER_UPDATE_HAS_ERRORED';
export const USER_LOGIN_HAS_ERRORED = 'USER_LOGIN_HAS_ERRORED';
